### ISSUE TITLE
Missing local config

### ISSUE THREAD

**Issue by antoineverger1** [arca223/yook-project#1]
Hey there,

I guess that there is either some missing README elements or some local config missing to have `make run` working:

![image](https://user-images.githubusercontent.com/43539846/117879756-9db37b00-b2a7-11eb-9841-c5bc638a0c96.png)

**Comment by arca223** [comment]
Oh yes, my bad, there is a need to cp the .env in .env.dev.local, at the
root directory
Something i've done at start which I forgot to put in the README.md

**Comment by antoineverger1** [comment]
But do I have to copy the .env as it is or do I have to fill it with some
params? For example, the db params are all empty, is that correct?
